"""Added MarkingFeedbackItem table

Revision ID: 9f592d69e1bc
Revises: d59880663eed
Create Date: 2026-03-17 12:08:35.360952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f592d69e1bc'
down_revision = 'd59880663eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marking_feedback_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('contents', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['marking_feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marking_feedback_items')
    # ### end Alembic commands ###
