"""empty message

Revision ID: d59880663eed
Revises: 69e2d134d5a3
Create Date: 2026-03-17 12:05:50.699666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59880663eed'
down_revision = '69e2d134d5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_feedback', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
